include:
  - movies.yml
  - anime.yml
  - shows.yml

settings:
  cache: false
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 3
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order: title.asc
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids: []
  ignore_imdb_ids: []
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user: []
  playlist_report: false
  verify_ssl: true
  custom_repo: []
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users: []
  run_order:
    - operations
    - metadata
    - collections
    - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 100
libraries:
  TV:
    plex:
      url: http://192.168.1.11:32400
      token: SeXYVFk1XooCAs8pYWbc
      timeout: 60
      clean_bundles: true
      empty_trash: true
      optimize: true
      db_cache: 4096
      verify_ssl: false
  Movies:
    plex:
      url: http://192.168.1.11:32400
      token: SeXYVFk1XooCAs8pYWbc
      timeout: 60
      clean_bundles: true
      empty_trash: true
      optimize: true
      db_cache: 4096
      verify_ssl: false
  Anime:
    plex:
      url: http://192.168.1.11:32400
      token: SeXYVFk1XooCAs8pYWbc
      timeout: 60
      clean_bundles: true
      empty_trash: true
      optimize: true
      db_cache: 4096
      verify_ssl: false
tmdb:
  apikey: d73f566cb3db023b2daddd906b595bd3
  language: en
  cache_expiration: 60
  region:
tautulli:
  url: https://tautulli.svendrive.com
  apikey: 592858a687b8467987b42e0ba2c86343
radarr:
  url: https://radarr.svendrive.com
  token: 9b68ef0dbe3e447bb833bafaa3bd3531
  version: v3
  add_missing: true
  root_folder_path: /Data/plex/movies
  monitor: true
  availability: released
  quality_profile: Remux + WEB 1080p
  tag:
  search: true
  add_existing: false
  upgrade_existing: true
  radarr_path:
  plex_path:
  ignore_cache: false
  monitor_existing: false
sonarr:
  url: https://sonarr.svendrive.com
  token: b3caae4636864ebe96b99bfa7100a816
  version: v4
  add_missing: true
  root_folder_path: /Data/plex/shows
  monitor: all
  quality_profile: WEB-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag: series
  search: true
  cutoff_search: false
  add_existing: false
  upgrade_existing: true
  sonarr_path:
  plex_path:
  ignore_cache: false
  monitor_existing: false
  # Add an additional section for Anime
  anime:
    quality_profile: Remux-1080p - Anime
    root_folder_path: /Data/plex/anime
    language_profile: dual_audio
    series_type: anime
    season_folder: true
    search: true
    monitor: true
    upgrade_existing: true
    ignore_cache: false

mal:
  client_id: b219fbf4b4a849aa9ef0bfda358296b8
  client_secret: e31e4d589d9e4a87852986ae801dc2f83ffdae67ac124b0422e4c05c6b7a55c0
  localhost_url: http://localhost/?code=def5020076017c566e00c2bd22451f0fe144951d55e83a46cf00e42c8951938ff4b76be3b276ce72e194957eea9d2eba92b52ad23a203ed7f45a8fc2e593e05693781dde31196017d367664c3aeb9d6157df5f17bfe4daf3019eb0400c1cecdb30d1d9923f7f1bd34f73cba8975508bc414b948eb6de5b0e4b4bb93b3c4ae10698bf402268a59435af702ebb92bf133cefc44e9705c992c3aede8c9c8c1283543ddc0747189bcd6f2f57d088a811c57fcc0fb2a3f7098aa8f6c0cf8107dc4320aa73cff37134e89621f3205b85c2af58280527d3a274e50f8b5725d1e551a5e8869a1d9d76370cbeaf685d0336ff5bc7480a331ccc5cc443e9fd5beb522d3e9a9b5850e7e1f58ec5da0c4abf9a5e869c57cbaeebd5e3125a50622d2ab7e621f32e9a184239a7cbe0556e6c50e8e61f1972a5fedf740a0f6063bcd3f75c664347388e09234501db994a7663ac165f5aa5d21a6a5ea8ea887dea30bb61f8bbee1080c31a0503babefb5dd497de8600f78f9fb1a8ecd1d25ee4f6848d11806e3d7a0c68579baa8239e05cba8c22616c3fbb9f4dbb56bb7e1e4abdebadbc538c845a6b88e7b965c7cbb6aa0d20bb569161442c547ab6ab2f8b3a203932279445d955a58a60664b7fd8cdb494f3c544ae19e05d9ed2da1b16f88933148456f26f471f3b5975b821af853bda
  authorization:
    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjZjNDVjZjlhNTY1YWNjYTMxYjAyYTEzNDYwOWFlMWE1OGVmMTNjNGMzMTZjOTc3OTFiNzFjZmU3MDU4MzIyNDg4MmRmMWZhZWY0ZDQzNjlmIn0.eyJhdWQiOiJiMjE5ZmJmNGI0YTg0OWFhOWVmMGJmZGEzNTgyOTZiOCIsImp0aSI6IjZjNDVjZjlhNTY1YWNjYTMxYjAyYTEzNDYwOWFlMWE1OGVmMTNjNGMzMTZjOTc3OTFiNzFjZmU3MDU4MzIyNDg4MmRmMWZhZWY0ZDQzNjlmIiwiaWF0IjoxNzI5NTg3NjQ5LCJuYmYiOjE3Mjk1ODc2NDksImV4cCI6MTczMjI2OTY0OSwic3ViIjoiNzQzNDcyOSIsInNjb3BlcyI6W119.P0qdVBRI-g4VpG8KlEp-THQuCfY3_R9nmJ3rfn0D-__WWvHmuppgFb00IjeKg4FlW4t0jBQWazM1kiJZNa2Lg8H3JKBurZAe75RUVq4g98JrZXj_BQarr3yAmN4OKabFMtspvkLfAtdDq8uQqVMXG_NQZuJqioitMU3yRZo1WGkDAK9ziAZencCzkr4tvW3TN6_Q6GWhbqr8ct-ErqSxPng5PPNfV5YXGrsh1Yiid3ekKS5zECr2O0f8krKHfZNy7a0lXzBvWJ5-CUT-_tJIwTqcvaPG5ldYZ2f7GmaxA3Osx5cI4a4Cw_zLBOVmfN6ixza1emsRuevTTKWpI_I4pw
    token_type: Bearer
    expires_in: 2682000
    refresh_token: def502009707703794a7fb49ab9ef0a8f9dd69aece0f5efc89000afa089de6fe78df9039c7293ce51aafb31d4a6a7f8b8633e50580bea2f2bb54153cfce4615f03ac475c8c4f704143585b96392a94841d640282e868c95cdf72e0e2d0504fc746e008d0393514c451443e8570acc2244adcd0b8c54981af99e823bf8c014c5460fde78ca1f254421ece45e14e2d1be5c038a6ae466bc074037f4d92a04b02a2f4479a725ac54ee098d7d3033b81c8ee7dea116705a86252985fda3929e57c28d2aadb4ba7fe720a5d9827e09b4fcafea5eb5fa81122e9c5e1e3e810be32b647b09b3bc47a97cf1d855bd319d67d2b156bbcb2adcb527531df399a40363e3aaa32f09ef65a6267395075ec824d103b1b3c9fa95a9869e4b50017619287062f153fd52f1f8ef318c9fa0d6594cc30bf7fff991e1b351cb1854b578b11f0366ce89c34eb8367d309ab20b9f2a2b98ea26f04e76901517fce22706e4e9411548cdd2e31c7cf93a0e86231a39a7d77ce82d6b5eb06f09de3b706fd15ad8e983f8f74b7341ec87f1b9168
  cache_expiration: 60
trakt:
  client_id: f89b4c6ac9b6bd2edcbc0bae1dc9038b4ef1f48d13d6f39c8993f35e5e1c459e
  client_secret: a5df6e9465efe29a3b8b696fb0693171b7e89de3f8e81c5c30c7ee4b7512df5f
# Everything below this line is automatically generated
  authorization:
    access_token: 624feba7dc542ad49183ab108a65b4d12e94d337160be454e91df9eb309538f5
    token_type: Bearer
    expires_in: 7889238
    refresh_token: a20dbbc7b728a5371bdcaf84e949576cc8a462f0dec1f3e24668019459d29a20
    scope: public
    created_at: 1732183221
  upgrade_existing: true
  sonarr_path:
  plex_path:
  pin:
